/**
 * Shared Release Checklist template — reused for every project.
 *
 * Projects store only status/remarks/uploads under data/release-checklists/.
 * Optional per-project overrides: projects/<id>/releaseChecklist.json
 *   { "disabledSections": ["android"], "disabledItems": ["web-pay"] }
 */

/** @typedef {'backend'|'web'|'ios'|'android'|'security'|'qa'|'golive'} SectionId */

/**
 * @typedef {{ id: string, label: string, evidence?: boolean }} ChecklistItemDef
 * @typedef {{ id: SectionId, title: string, subtitle?: string, items: ChecklistItemDef[], upload?: 'web'|'ios'|'android' }} SectionDef
 */

/** Item status values stored per project/env. */
const ITEM_STATUSES = [
  'not_started',
  'in_progress',
  'completed',
  'blocked',
  'na',
];

const ENVIRONMENTS = ['production', 'staging'];

/** Deployment / store pipeline statuses (independent of item checkmarks). */
const UPLOAD_STATUSES = {
  web: ['not_started', 'uploaded', 'deployed', 'verified', 'failed'],
  ios: [
    'not_started',
    'build_ready',
    'uploaded',
    'processing',
    'testflight',
    'qa_approved',
    'client_approved',
    'submitted',
    'app_review',
    'approved',
    'released',
    'rejected',
  ],
  android: [
    'not_started',
    'build_ready',
    'uploaded',
    'internal_testing',
    'qa_approved',
    'client_approved',
    'closed_testing',
    'production_ready',
    'submitted',
    'review',
    'released',
    'rejected',
  ],
};

/** @type {SectionDef[]} */
const SECTIONS = [
  {
    id: 'backend',
    title: 'Backend / API Production',
    subtitle: 'Branch, build, DB, auth, integrations, monitoring',
    items: [
      { id: 'be-branch', label: 'Production branch/tag confirmed', evidence: true },
      { id: 'be-build', label: 'Production build created', evidence: true },
      { id: 'be-env', label: 'Production environment variables configured' },
      { id: 'be-api-url', label: 'Production API URL verified', evidence: true },
      { id: 'be-db-backup', label: 'Database backup completed', evidence: true },
      { id: 'be-db-migrate', label: 'Database migration completed', evidence: true },
      { id: 'be-db-verify', label: 'Database migration verified' },
      { id: 'be-data', label: 'Existing production data verified' },
      { id: 'be-auth', label: 'Authentication tested' },
      { id: 'be-roles', label: 'Authorization/roles tested' },
      { id: 'be-validation', label: 'API validation tested' },
      { id: 'be-errors', label: 'Error handling verified' },
      { id: 'be-files', label: 'File upload/download tested' },
      { id: 'be-thirdparty', label: 'Third-party integrations verified' },
      { id: 'be-payments', label: 'Payment gateway production configuration verified' },
      { id: 'be-messaging', label: 'Email/SMS/WhatsApp configuration verified' },
      { id: 'be-push', label: 'Push notification configuration verified' },
      { id: 'be-webhooks', label: 'Webhooks configured' },
      { id: 'be-ssl', label: 'SSL/HTTPS verified' },
      { id: 'be-monitor', label: 'Server monitoring enabled' },
      { id: 'be-error-mon', label: 'Error monitoring enabled' },
      { id: 'be-backup-sched', label: 'Backup schedule verified' },
      { id: 'be-rollback', label: 'Rollback plan confirmed', evidence: true },
      { id: 'be-deploy', label: 'Backend production deployment completed', evidence: true },
      { id: 'be-smoke', label: 'Production smoke test completed', evidence: true },
    ],
  },
  {
    id: 'web',
    title: 'Web Panel',
    subtitle: 'Build, configuration, upload/deploy, functional QA',
    upload: 'web',
    items: [
      { id: 'web-branch', label: 'Production branch confirmed' },
      { id: 'web-build', label: 'Production build generated', evidence: true },
      { id: 'web-api', label: 'Production API URL configured' },
      { id: 'web-env', label: 'Environment variables verified' },
      { id: 'web-domain', label: 'Production domain verified', evidence: true },
      { id: 'web-ssl', label: 'SSL verified' },
      { id: 'web-cdn', label: 'CDN/cache verified' },
      { id: 'web-no-dev-api', label: 'No development/test API URLs' },
      { id: 'web-no-debug', label: 'Debug logs removed' },
      { id: 'web-no-testdata', label: 'Test data removed' },
      { id: 'web-upload', label: 'Web build uploaded / attached', evidence: true },
      { id: 'web-deployed', label: 'Web deployment completed', evidence: true },
      { id: 'web-verified', label: 'Web deployment verified' },
      { id: 'web-fn-login', label: 'Login' },
      { id: 'web-fn-logout', label: 'Logout' },
      { id: 'web-fn-forgot', label: 'Forgot Password' },
      { id: 'web-fn-dash', label: 'Dashboard' },
      { id: 'web-fn-users', label: 'User Management' },
      { id: 'web-fn-customers', label: 'Customer/Owner Management' },
      { id: 'web-fn-patients', label: 'Animal/Patient Management' },
      { id: 'web-fn-booking', label: 'Booking/Request Management' },
      { id: 'web-fn-search', label: 'Search' },
      { id: 'web-fn-filter', label: 'Filter' },
      { id: 'web-fn-paging', label: 'Pagination' },
      { id: 'web-fn-create', label: 'Create' },
      { id: 'web-fn-edit', label: 'Edit' },
      { id: 'web-fn-delete', label: 'Delete/Deactivate' },
      { id: 'web-fn-reports', label: 'Reports' },
      { id: 'web-fn-export', label: 'Export/Download' },
      { id: 'web-fn-file', label: 'File Upload' },
      { id: 'web-fn-notify', label: 'Notifications' },
      { id: 'web-fn-settings', label: 'Settings' },
      { id: 'web-fn-roles', label: 'Role/Permission testing' },
      { id: 'web-browser-chrome', label: 'Chrome testing' },
      { id: 'web-browser-safari', label: 'Safari testing' },
      { id: 'web-browser-firefox', label: 'Firefox testing' },
      { id: 'web-browser-edge', label: 'Edge testing' },
      { id: 'web-responsive', label: 'Responsive testing' },
    ],
  },
  {
    id: 'ios',
    title: 'iOS',
    subtitle: 'Signing, archive, App Store / TestFlight, functional QA',
    upload: 'ios',
    items: [
      { id: 'ios-account', label: 'Apple Developer account verified' },
      { id: 'ios-bundle', label: 'Bundle ID verified' },
      { id: 'ios-cert', label: 'Distribution certificate verified' },
      { id: 'ios-profile', label: 'Provisioning profile verified' },
      { id: 'ios-push', label: 'Push notification configuration verified' },
      { id: 'ios-domains', label: 'Associated Domains verified if required' },
      { id: 'ios-api', label: 'Production API URL configured' },
      { id: 'ios-env', label: 'Production environment configured' },
      { id: 'ios-version', label: 'Version number updated' },
      { id: 'ios-buildno', label: 'Build number updated' },
      { id: 'ios-icon', label: 'App icon verified' },
      { id: 'ios-splash', label: 'Splash screen verified' },
      { id: 'ios-no-debug', label: 'Debug configuration removed' },
      { id: 'ios-no-mock', label: 'Test/mock data removed' },
      { id: 'ios-archive', label: 'Production archive created', evidence: true },
      { id: 'ios-upload', label: 'iOS build uploaded / attached', evidence: true },
      { id: 'ios-testflight', label: 'TestFlight available' },
      { id: 'ios-qa', label: 'QA approved' },
      { id: 'ios-client', label: 'Client approved' },
      { id: 'ios-submitted', label: 'Submitted to App Store' },
      { id: 'ios-review', label: 'App Review passed' },
      { id: 'ios-released', label: 'Released on App Store', evidence: true },
      { id: 'ios-fn-fresh', label: 'Fresh installation' },
      { id: 'ios-fn-upgrade', label: 'Existing-user upgrade' },
      { id: 'ios-fn-login', label: 'Login' },
      { id: 'ios-fn-reg', label: 'Registration' },
      { id: 'ios-fn-otp', label: 'OTP' },
      { id: 'ios-fn-logout', label: 'Logout' },
      { id: 'ios-fn-reset', label: 'Password reset' },
      { id: 'ios-fn-nav', label: 'Main navigation' },
      { id: 'ios-fn-workflow', label: 'Main business workflow' },
      { id: 'ios-fn-create', label: 'Create operation' },
      { id: 'ios-fn-update', label: 'Update operation' },
      { id: 'ios-fn-delete', label: 'Delete/Cancel operation' },
      { id: 'ios-fn-camera', label: 'Camera' },
      { id: 'ios-fn-gallery', label: 'Gallery' },
      { id: 'ios-fn-file', label: 'File upload' },
      { id: 'ios-fn-push', label: 'Push notification' },
      { id: 'ios-fn-deeplink', label: 'Deep link' },
      { id: 'ios-fn-pay', label: 'Payment if applicable' },
      { id: 'ios-fn-session', label: 'Session expiry' },
      { id: 'ios-fn-bg', label: 'Background/Foreground' },
      { id: 'ios-fn-force', label: 'Force close/Reopen' },
      { id: 'ios-fn-keyboard', label: 'Keyboard behavior' },
      { id: 'ios-fn-perms', label: 'Permission handling' },
      { id: 'ios-fn-minos', label: 'Minimum supported iOS' },
      { id: 'ios-fn-latestos', label: 'Latest supported iOS' },
      { id: 'ios-fn-small', label: 'Small screen device' },
      { id: 'ios-fn-large', label: 'Large screen device' },
    ],
  },
  {
    id: 'android',
    title: 'Android',
    subtitle: 'Signing, AAB, Play Console, functional QA',
    upload: 'android',
    items: [
      { id: 'and-account', label: 'Google Play Developer account verified' },
      { id: 'and-package', label: 'Package/Application ID verified' },
      { id: 'and-signing', label: 'Play App Signing verified' },
      { id: 'and-upload-key', label: 'Upload key verified' },
      { id: 'and-api', label: 'Production API URL configured' },
      { id: 'and-env', label: 'Production environment configured' },
      { id: 'and-version-name', label: 'Version Name updated' },
      { id: 'and-version-code', label: 'Version Code increased' },
      { id: 'and-icon', label: 'App icon verified' },
      { id: 'and-splash', label: 'Splash screen verified' },
      { id: 'and-no-debug', label: 'Debug configuration removed' },
      { id: 'and-no-mock', label: 'Test/mock data removed' },
      { id: 'and-aab', label: 'Production AAB generated', evidence: true },
      { id: 'and-upload', label: 'AAB uploaded / attached', evidence: true },
      { id: 'and-internal', label: 'Internal testing available' },
      { id: 'and-qa', label: 'QA approved' },
      { id: 'and-client', label: 'Client approved' },
      { id: 'and-closed', label: 'Closed testing (if used)' },
      { id: 'and-prod-ready', label: 'Production ready' },
      { id: 'and-submitted', label: 'Submitted to Play' },
      { id: 'and-review', label: 'Play Review passed' },
      { id: 'and-released', label: 'Released on Google Play', evidence: true },
      { id: 'and-fn-fresh', label: 'Fresh installation' },
      { id: 'and-fn-upgrade', label: 'Existing-user upgrade' },
      { id: 'and-fn-login', label: 'Login' },
      { id: 'and-fn-reg', label: 'Registration' },
      { id: 'and-fn-otp', label: 'OTP' },
      { id: 'and-fn-logout', label: 'Logout' },
      { id: 'and-fn-reset', label: 'Password reset' },
      { id: 'and-fn-nav', label: 'Main navigation' },
      { id: 'and-fn-workflow', label: 'Main business workflow' },
      { id: 'and-fn-create', label: 'Create operation' },
      { id: 'and-fn-update', label: 'Update operation' },
      { id: 'and-fn-delete', label: 'Delete/Cancel' },
      { id: 'and-fn-camera', label: 'Camera' },
      { id: 'and-fn-gallery', label: 'Gallery' },
      { id: 'and-fn-file', label: 'File upload' },
      { id: 'and-fn-push', label: 'Push notification' },
      { id: 'and-fn-deeplink', label: 'Deep link' },
      { id: 'and-fn-pay', label: 'Payment if applicable' },
      { id: 'and-fn-session', label: 'Session expiry' },
      { id: 'and-fn-bg', label: 'Background/Foreground' },
      { id: 'and-fn-force', label: 'Force close/Reopen' },
      { id: 'and-fn-keyboard', label: 'Keyboard behavior' },
      { id: 'and-fn-perms', label: 'Permissions' },
      { id: 'and-fn-min', label: 'Minimum Android version' },
      { id: 'and-fn-latest', label: 'Latest Android version' },
      { id: 'and-fn-screens', label: 'Different screen sizes' },
      { id: 'and-fn-devices', label: 'Different Android devices if applicable' },
    ],
  },
  {
    id: 'security',
    title: 'Security',
    subtitle: 'Secrets, auth, access, scanning',
    items: [
      { id: 'sec-https', label: 'HTTPS enabled' },
      { id: 'sec-no-secrets', label: 'No production secrets in source code' },
      { id: 'sec-keys', label: 'API keys secured' },
      { id: 'sec-auth', label: 'Authentication verified' },
      { id: 'sec-authz', label: 'Authorization verified' },
      { id: 'sec-token', label: 'Token expiry verified' },
      { id: 'sec-refresh', label: 'Refresh token verified' },
      { id: 'sec-upload', label: 'File upload security verified' },
      { id: 'sec-rate', label: 'Rate limiting verified' },
      { id: 'sec-admin', label: 'Admin access verified' },
      { id: 'sec-db', label: 'Database access restricted' },
      { id: 'sec-creds', label: 'Production credentials secured' },
      { id: 'sec-scan', label: 'Security scan completed', evidence: true },
    ],
  },
  {
    id: 'qa',
    title: 'Final QA / UAT',
    subtitle: 'Smoke, regression, automation, client sign-off',
    items: [
      { id: 'qa-smoke', label: 'Smoke testing completed', evidence: true },
      { id: 'qa-regression', label: 'Regression testing completed', evidence: true },
      { id: 'qa-automation', label: 'Automation testing completed', evidence: true },
      { id: 'qa-critical', label: 'Critical workflows tested' },
      { id: 'qa-no-p0', label: 'No P0 issues' },
      { id: 'qa-no-p1', label: 'No P1 issues' },
      { id: 'qa-known', label: 'Known issues documented', evidence: true },
      { id: 'qa-client-qa', label: 'Client QA completed' },
      { id: 'qa-client-uat', label: 'Client UAT completed' },
      { id: 'qa-feedback', label: 'Client feedback addressed' },
      { id: 'qa-approval', label: 'Client approval received', evidence: true },
    ],
  },
  {
    id: 'golive',
    title: 'Go-Live',
    subtitle: 'Final cutover checklist',
    items: [
      { id: 'gl-backup', label: 'Database backup completed', evidence: true },
      { id: 'gl-backend', label: 'Backend deployed' },
      { id: 'gl-web', label: 'Web deployed' },
      { id: 'gl-ios', label: 'iOS uploaded' },
      { id: 'gl-android', label: 'Android uploaded' },
      { id: 'gl-smoke', label: 'Production smoke testing completed', evidence: true },
      { id: 'gl-monitor', label: 'Monitoring enabled' },
      { id: 'gl-crash', label: 'Crash monitoring enabled' },
      { id: 'gl-api-mon', label: 'API monitoring enabled' },
      { id: 'gl-support', label: 'Support team informed' },
      { id: 'gl-notes', label: 'Release notes prepared', evidence: true },
      { id: 'gl-rollback', label: 'Rollback plan confirmed' },
      { id: 'gl-client', label: 'Client final approval received', evidence: true },
      { id: 'gl-done', label: 'Release completed', evidence: true },
    ],
  },
];

/**
 * Flat map of item id → section id for lookups.
 * @returns {Map<string, SectionId>}
 */
function itemSectionMap() {
  const map = new Map();
  for (const section of SECTIONS) {
    for (const item of section.items) {
      map.set(item.id, section.id);
    }
  }
  return map;
}

module.exports = {
  SECTIONS,
  ITEM_STATUSES,
  ENVIRONMENTS,
  UPLOAD_STATUSES,
  itemSectionMap,
};
