/**
 * Read / write project .env files for setup wizards.
 * Preserves unknown keys; updates known keys in place when possible.
 */
const fs = require('fs');
const path = require('path');

/**
 * Parse KEY=VALUE lines (simple dotenv subset).
 * @param {string} text
 * @returns {Record<string, string>}
 */
function parseEnv(text) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1);
    // Strip matching quotes
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

/**
 * @param {string} envPath
 * @returns {Record<string, string>}
 */
function readEnvFile(envPath) {
  if (!fs.existsSync(envPath)) return {};
  return parseEnv(fs.readFileSync(envPath, 'utf8'));
}

/**
 * Merge updates into an existing .env (or example) text, preserving comments/order.
 * New keys are appended under a "Generated by setup" block.
 * @param {string} existingText
 * @param {Record<string, string>} updates
 * @returns {string}
 */
function mergeEnvText(existingText, updates) {
  const keys = Object.keys(updates);
  const seen = new Set();
  const lines = existingText.split(/\r?\n/);
  const next = lines.map((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return line;
    const eq = trimmed.indexOf('=');
    if (eq === -1) return line;
    const key = trimmed.slice(0, eq).trim();
    if (Object.prototype.hasOwnProperty.call(updates, key)) {
      seen.add(key);
      return `${key}=${updates[key]}`;
    }
    return line;
  });

  const missing = keys.filter((k) => !seen.has(k));
  if (missing.length) {
    if (next.length && next[next.length - 1] !== '') next.push('');
    next.push('# --- Written by setup wizard ---');
    for (const key of missing) {
      next.push(`${key}=${updates[key]}`);
    }
  }
  return `${next.join('\n').replace(/\n+$/, '')}\n`;
}

/**
 * Write .env from example + updates.
 * @param {object} opts
 * @param {string} opts.projectPath
 * @param {Record<string, string>} opts.updates
 * @returns {string} path written
 */
function writeProjectEnv({ projectPath, updates }) {
  const envPath = path.join(projectPath, '.env');
  const examplePath = path.join(projectPath, '.env.example');
  let base = '';
  if (fs.existsSync(envPath)) {
    base = fs.readFileSync(envPath, 'utf8');
  } else if (fs.existsSync(examplePath)) {
    base = fs.readFileSync(examplePath, 'utf8');
  } else {
    base = Object.entries(updates)
      .map(([k, v]) => `${k}=${v}`)
      .join('\n');
    fs.writeFileSync(envPath, `${base}\n`, 'utf8');
    return envPath;
  }
  const merged = mergeEnvText(base, updates);
  fs.writeFileSync(envPath, merged, 'utf8');
  return envPath;
}

module.exports = {
  parseEnv,
  readEnvFile,
  mergeEnvText,
  writeProjectEnv,
};
