/**
 * Ask which language the user wants for automation scripts.
 * This repo currently scaffolds and runs JavaScript (WebdriverIO) only.
 */
const { askChoice, askYesNo } = require('./prompt');

/**
 * @typedef {'javascript' | 'python'} ScriptLanguage
 */

/**
 * Prompt for script language. Python is acknowledged but not scaffolded yet.
 * @param {{ assumeJavascript?: boolean }} [opts]
 * @returns {Promise<ScriptLanguage>}
 */
async function askScriptLanguage(opts = {}) {
  if (opts.assumeJavascript) {
    return 'javascript';
  }

  console.log('\n=== Script language ===');
  console.log('  This repo’s framework today: JavaScript (WebdriverIO + Appium).');
  console.log('  Python is a common alternative, but is not scaffolded here yet.');

  const pick = await askChoice(
    'Which language do you want to write automation scripts in?',
    [
      'JavaScript (recommended — matches this repo)',
      'Python (not supported by this framework yet)',
    ],
    0,
  );

  if (pick.startsWith('JavaScript')) {
    return 'javascript';
  }

  console.log(`
  You chose Python.
  VetPal / RosKids / new projects in this repo use JavaScript (WebdriverIO).
  A Python Appium stack is not generated by this wizard yet.
`);

  const continueJs = await askYesNo(
    'Continue setup using JavaScript for this project anyway?',
    true,
  );
  if (!continueJs) {
    console.log(
      '\nSetup cancelled. Stay on this JS framework, or plan a separate Python Appium project.\n',
    );
    process.exit(0);
  }

  console.log('  Continuing with JavaScript.\n');
  return 'javascript';
}

module.exports = { askScriptLanguage };
